"""empty message

Revision ID: 09667301a641
Revises: 
Create Date: 2024-11-18 15:54:07.126051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09667301a641'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_empresa', sa.String(length=20), nullable=False),
    sa.Column('apel_emp', sa.String(length=100), nullable=False),
    sa.Column('nome_emp', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('cnpj_base', sa.String(length=8), nullable=False),
    sa.Column('razao_social', sa.String(length=100), nullable=True),
    sa.Column('ijuc_emp', sa.String(length=50), nullable=True),
    sa.Column('dcad_emp', sa.Date(), nullable=True),
    sa.Column('stat_emp', sa.String(length=1), nullable=True),
    sa.Column('cida_emp', sa.String(length=100), nullable=True),
    sa.Column('esta_emp', sa.String(length=2), nullable=True),
    sa.Column('iest_emp', sa.String(length=50), nullable=True),
    sa.Column('imun_emp', sa.String(length=50), nullable=True),
    sa.Column('njud_emp', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_empresa')
    )
    op.create_table('tipo_alvara',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('can_add', sa.Boolean(), nullable=True),
    sa.Column('can_edit', sa.Boolean(), nullable=True),
    sa.Column('can_delete', sa.Boolean(), nullable=True),
    sa.Column('can_export', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('alvara',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('responsavel', sa.String(length=100), nullable=False),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('anexo', sa.String(length=200), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('codigo_empresa', sa.String(length=20), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('razao_social', sa.String(length=100), nullable=False),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('arquivo', sa.String(length=200), nullable=True),
    sa.Column('senha', sa.String(length=100), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('algoritmo_assinatura', sa.String(length=100), nullable=True),
    sa.Column('issuer', sa.String(length=200), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responsavel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], name='fk_responsavel_usuario_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', name='uq_responsavel_nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responsavel')
    op.drop_table('certificado')
    op.drop_table('alvara')
    op.drop_table('user')
    op.drop_table('tipo_alvara')
    op.drop_table('empresa')
    # ### end Alembic commands ###
