"""Add ecpf model

Revision ID: 0a40b5ac9b1d
Revises: ab459007735c
Create Date: 2025-02-10 14:11:05.581272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a40b5ac9b1d'
down_revision = 'ab459007735c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alvara', schema=None) as batch_op:
        batch_op.drop_column('pendente')
        batch_op.drop_column('localizador')
        batch_op.drop_column('em_renovacao')
        batch_op.drop_column('arquivado')
        batch_op.drop_column('licenciamento')

    with op.batch_alter_table('certificado_ecpf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codi_emp', sa.String(length=20), nullable=True))
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_column('codigo_empresa')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificado_ecpf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_empresa', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)
        batch_op.drop_column('codi_emp')

    with op.batch_alter_table('alvara', schema=None) as batch_op:
        batch_op.add_column(sa.Column('licenciamento', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('arquivado', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('em_renovacao', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('localizador', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('pendente', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
