"""add data assinatura extenso contrato

Revision ID: 1425b9707eb1
Revises: 5500480e1607
Create Date: 2026-04-30 14:16:57.199221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1425b9707eb1'
down_revision = '5500480e1607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_assinatura_extenso', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.drop_column('data_assinatura_extenso')

    # ### end Alembic commands ###
