"""Adiciona campo notificacao_dias em Alvara

Revision ID: 35fde6651773
Revises: 09667301a641
Create Date: 2024-11-21 17:16:31.836331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35fde6651773'
down_revision = '09667301a641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alvara', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notificacao_dias', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alvara', schema=None) as batch_op:
        batch_op.drop_column('notificacao_dias')

    # ### end Alembic commands ###
