"""add tabela assessoria

Revision ID: 3f869d251f37
Revises: c1388898042e
Create Date: 2026-07-03 20:43:33.057569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f869d251f37'
down_revision = 'c1388898042e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('logradouro', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=30), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('crc_empresa', sa.String(length=50), nullable=True),
    sa.Column('representante_nome', sa.String(length=200), nullable=True),
    sa.Column('representante_cpf', sa.String(length=20), nullable=True),
    sa.Column('representante_crc', sa.String(length=50), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessoria')
    # ### end Alembic commands ###
