"""add contrato model

Revision ID: 5500480e1607
Revises: cdbdbc997220
Create Date: 2026-04-28 13:55:50.492387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5500480e1607'
down_revision = 'cdbdbc997220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_contrato', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('codigo_empresa', sa.String(length=20), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('rua', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=30), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('socio_administrador', sa.String(length=200), nullable=True),
    sa.Column('cpf_socio', sa.String(length=20), nullable=True),
    sa.Column('vigencia', sa.Date(), nullable=True),
    sa.Column('vigencia_extenso', sa.String(length=100), nullable=True),
    sa.Column('regime_tributacao', sa.String(length=50), nullable=True),
    sa.Column('regime_apuracao', sa.String(length=50), nullable=True),
    sa.Column('periodicidade_demonstrativos', sa.String(length=50), nullable=True),
    sa.Column('honorario_mensal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('honorario_mensal_extenso', sa.String(length=300), nullable=True),
    sa.Column('encerramento_obrigacoes', sa.Date(), nullable=True),
    sa.Column('encerramento_obrigacoes_extenso', sa.String(length=100), nullable=True),
    sa.Column('valor_inadimplencia', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valor_inadimplencia_extenso', sa.String(length=300), nullable=True),
    sa.Column('meses_pendentes', sa.Text(), nullable=True),
    sa.Column('arquivo_docx', sa.String(length=300), nullable=True),
    sa.Column('arquivo_pdf', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contrato')
    # ### end Alembic commands ###
