"""Add empresa_contratada to contrato

Revision ID: a6484866e8fb
Revises: e10d61ec6be9
Create Date: 2026-05-25 09:42:21.095520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6484866e8fb'
down_revision = 'e10d61ec6be9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_contratada', sa.String(length=50), server_default='scryta', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.drop_column('empresa_contratada')

    # ### end Alembic commands ###
