"""Alvaras alteracao

Revision ID: ab459007735c
Revises: abc3c27a61ee
Create Date: 2025-02-07 15:54:10.576976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab459007735c'
down_revision = 'abc3c27a61ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alvara', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arquivado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('em_renovacao', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pendente', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('licenciamento', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('localizador', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alvara', schema=None) as batch_op:
        batch_op.drop_column('localizador')
        batch_op.drop_column('licenciamento')
        batch_op.drop_column('pendente')
        batch_op.drop_column('em_renovacao')
        batch_op.drop_column('arquivado')

    # ### end Alembic commands ###
