"""empty message

Revision ID: abc3c27a61ee
Revises: 35fde6651773
Create Date: 2024-12-10 08:47:10.685450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc3c27a61ee'
down_revision = '35fde6651773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alvara', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dispensada', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('indeterminada', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alvara', schema=None) as batch_op:
        batch_op.drop_column('indeterminada')
        batch_op.drop_column('dispensada')

    # ### end Alembic commands ###
