"""adiciona coluna distratante_inverso em contrato

Revision ID: c6af3ae5b867
Revises: a6484866e8fb
Create Date: 2026-05-26 09:34:04.463563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6af3ae5b867'
down_revision = 'a6484866e8fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distratante_inverso', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.drop_column('distratante_inverso')

    # ### end Alembic commands ###
