"""Adiciona tabela NotificacaoTrello

Revision ID: cdbdbc997220
Revises: da47566e0345
Create Date: 2025-07-24 09:16:49.382543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdbdbc997220'
down_revision = 'da47566e0345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacao_trello',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_empresa', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('validade', sa.Date(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_empresa', 'tipo', 'validade', name='uq_notificacao_empresa_tipo_validade')
    )
    op.drop_table('certificado_card')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificado_card',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('certificado_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['certificado_id'], ['certificado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('notificacao_trello')
    # ### end Alembic commands ###
