"""empty message

Revision ID: da47566e0345
Revises: 0a40b5ac9b1d
Create Date: 2025-02-28 13:11:32.551523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da47566e0345'
down_revision = '0a40b5ac9b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alvara', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arquivado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('em_renovacao', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pendente', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alvara', schema=None) as batch_op:
        batch_op.drop_column('pendente')
        batch_op.drop_column('em_renovacao')
        batch_op.drop_column('arquivado')

    # ### end Alembic commands ###
