"""add notificacao validade

Revision ID: e9479de0c560
Revises: c6af3ae5b867
Create Date: 2026-05-29 15:26:47.886333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9479de0c560'
down_revision = 'c6af3ae5b867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacao_validade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave_local', sa.String(length=255), nullable=False),
    sa.Column('codigo_empresa', sa.String(length=20), nullable=False),
    sa.Column('tipo_notificacao', sa.String(length=30), nullable=False),
    sa.Column('origem', sa.String(length=50), nullable=False),
    sa.Column('validade', sa.Date(), nullable=False),
    sa.Column('destino', sa.String(length=50), nullable=False),
    sa.Column('status_envio', sa.String(length=30), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave_local', 'destino', name='uq_notificacao_validade_chave_destino')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacao_validade')
    # ### end Alembic commands ###
